#DHCPSNP = DHCP SNOOPING
DHCPSNP_BASE_DIR		= $(BASE_DIR)/l2dhcsnp

DHCPSNP_INC_DIR		= $(DHCPSNP_BASE_DIR)/inc
DHCPSNP_SRC_DIR		= $(DHCPSNP_BASE_DIR)/src
DHCPSNP_OBJ_DIR		= $(DHCPSNP_BASE_DIR)/obj
DHCPSNP_DIRS		= $(DHCPSNP_INC_DIR)  $(DHCPSNP_SRC_DIR)  $(DHCPSNP_OBJ_DIR)
DHCPSNP_RMS		= $(DHCPSNP_OBJ_DIR)/*

DHCPSNP_SRC		= $(wildcard $(DHCPSNP_SRC_DIR)/*.c)
DHCPSNP_OBJ		= $(DHCPSNP_SRC:.c=.${ObjSuffix})
DHCPSNP_OBJ		:= $(patsubst $(DHCPSNP_SRC_DIR)/%, $(DHCPSNP_OBJ_DIR)/%, $(DHCPSNP_OBJ)) 
DHCPSNP_DEP		= $(DHCPSNP_SRC:.c=.${ObjSuffix}.dep)
DHCPSNP_DEP		:= $(patsubst $(DHCPSNP_SRC_DIR)/%, $(DHCPSNP_OBJ_DIR)/%, $(DHCPSNP_DEP)) 

DHCPSNP_INCLUDE_DIRS	= $(COMMON_INCLUDE_DIRS) \
			-I${BASE_DIR}/cfa2/inc \
			-I${BASE_DIR}/ISS/common/system/inc \
			-I${BASE_DIR}/snmpv3 \
			-I$(DHCPSNP_INC_DIR) 
TOTAL_OPNS		= $(GENERAL_COMPILATION_SWITCHES) $(SYSTEM_COMPILATION_SWITCHES)
DHCPSNP_CC_FLAGS		= $(CC_FLAGS) $(DHCPSNP_INCLUDE_DIRS) $(TOTAL_OPNS)

